CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES = *.pvsm Makefile.dist MANIFEST
RELDISTFILES = $(DISTFILES) $(shell cat MANIFEST)

dist:
	mkdir $(DESTDIR)
	-cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	-cp -fpd $(RELDISTFILES) $(DESTDIR)
