#!/usr/bin/python

"""Python shell for SfePy.

   This is just a normal Python shell (IPython shell if you have the
   IPython package installed),  that executes the following commands
   for the user:

       >>> from sfepy.base.base import *
       >>> from sfepy.fem import *

   So starting 'isfepy' is equivalent to starting Python (or IPython)
   and executing the above commands by hand. It is intended for easy
   and quick experimentation with SfePy.

   COMMAND LINE OPTIONS
   --------------------

   -c CONSOLE, --console=CONSOLE

     Use the specified Python or IPython shell as console backend instead
     of the default one (IPython if present or Python otherwise), e.g.:

        isfepy -c python

   -q, --quiet

     Print only Python's and SfePy's versions to stdout at startup.

   -- IPython's options

     Additionally you can pass command line options directly to IPython
     interpreter (standard Python shell is not supported).  However you
     need to add '--' separator between two types of options. To run
     SfePy without startup banner and colors, for example, issue:

        isfepy -q -- -colors NoColor

"""
import os, sys
from optparse import OptionParser

import sfepy
from sfepy.interactive import init_session

startup_message = """\
These commands were executed:
>>> from sfepy.base.base import *
>>> from sfepy.fem import *

Documentation can be found at http://sfepy.org
"""

no_ipython = """\
Couldn't locate IPython. Having IPython installed is greatly recommended. See
http://ipython.scipy.org for more details. You can try to install the 'ipython'
package and start isfepy again.
"""

usage = 'usage: isfepy [options] -- [ipython options]'
help = {
    'console' :
    'select type of interactive session: ipython | python [default: %default]',
    'quiet' :
    'print only version information at startup',
}


def main():
    py_version = "%d.%d.%d" % sys.version_info[:3]

    parser = OptionParser(usage=usage, version="%prog " + sfepy.__version__)
    parser.add_option('-c', '--console', dest='console', action='store',
                      default='ipython', help=help['console'])
    parser.add_option('-q', '--quiet', dest='quiet', action='store_true',
                      default=False, help=help['quiet'])
    options, ipy_args = parser.parse_args()

    session = options.console.lower()

    args = {
        'argv'        : ipy_args,
    }
    if not options.quiet:
        args['message'] = startup_message

    try:
        init_session(session, **args)
    except ValueError:
        try:
            init_session('ipython', **args)
        except ImportError:
            print no_ipython
            init_session('python', **args)

if __name__ == "__main__":
    main()
