# 29.05.2007, c
# last revision: 26.03.2008

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(shell ls *.py) Makefile.dist Makefile.inc MANIFEST

RELDISTFILES := Makefile.dist Makefile.inc MANIFEST $(shell cat MANIFEST)

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
