CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(wildcard *.py) Makefile.dist Makefile.inc MANIFEST

RELDISTFILES := $(DISTFILES)

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
