# 14.12.2004, c
# last revision: 26.02.2007

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(shell ls *.py *.c *.h *.i *.in) Makefile.dist Makefile.inc
DISTFILES := $(filter-out $(shell ls *_wrap.c), $(DISTFILES))

RELDISTFILES := $(filter-out  $(shell ls termsAdjointNavierStokes.*) $(shell ls termsHDPM.*), $(DISTFILES))

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
