CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(wildcard *.py *.c *.h *.i *.in) Makefile.dist Makefile.inc
DISTFILES := $(filter-out $(wildcard *_wrap.c), $(DISTFILES))

dist:
	mkdir $(DESTDIR)
	cp -fa $(DISTFILES) $(DESTDIR)

reldist: dist
