CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(shell ls *.py) Makefile.dist Makefile.inc
RELDISTFILES := $(DISTFILES)

dist:
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
        mkdir $(DESTDIR)
        cp -fpd $(RELDISTFILES) $(DESTDIR)
