# 02.05.2005, c
# last revision: 12.01.2007

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES = *.txt Makefile.dist

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	-cp -fpd $(DISTFILES) $(DESTDIR)

reldist: dist
