CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(wildcard *.py) Makefile.dist
DISTDIRS := $(shell find * -type d)

dist:
	mkdir -p $(DESTDIR)
	cp -fa $(DISTFILES) $(DESTDIR)
	-@for i in $(DISTDIRS); do \
		$(MAKE) -C $$i -f Makefile.dist $@ DISTDIR=${DESTDIR}/$$i; \
	done

reldist: dist
