# c: 05.05.2008, r: 05.05.2008
CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(wildcard *.py) Makefile.dist Makefile.inc MANIFEST
DISTDIRS :=

RELDISTFILES := $(DISTFILES) $(shell cat MANIFEST)
RELDISTDIRS := $(DISTDIRS)

dist:
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
