# 23.10.2007, c
# last revision: 23.10.2007

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := Makefile.dist

RELDISTFILES := $(DISTFILES) $(wildcard *.mesh) $(wildcard *.geo)

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
