# 04.10.2005, c
# last revision: 27.08.2007

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES = *.py *.pl *.sh *.m kill_* Makefile.dist
RELDISTFILES = *.py .sh kill_* Makefile.dist

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	cp -fpd $(RELDISTFILES) $(DESTDIR)
