CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES := $(wildcard *.py) Makefile.dist Makefile.inc
DISTDIRS := extmods

dist:
#	echo $(DESTDIR)
	mkdir $(DESTDIR)
	cp -fpd $(DISTFILES) $(DESTDIR)
	@for i in $(DISTDIRS); do \
	  $(MAKE) -C $$i -f Makefile.dist dist DISTDIR=${DESTDIR}; \
	done

reldist: dist
