# c: 24.01.2008
# last revision: 26.03.2008

CDIR = $(notdir $(CURDIR))
DESTDIR = $(DISTDIR)/$(CDIR)

DISTFILES = *.tex *.fig *.latex *.xml Makefile.dist
RELDISTFILES = $(DISTFILES)

dist:
	mkdir $(DESTDIR)
	-cp -fpd $(DISTFILES) $(DESTDIR)

reldist:
	mkdir $(DESTDIR)
	-cp -fpd $(RELDISTFILES) $(DESTDIR)
