# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _meshutils
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


PRINTF64 = _meshutils.PRINTF64
SCANF64 = _meshutils.SCANF64
SCANI16 = _meshutils.SCANI16
TYPE_Char = _meshutils.TYPE_Char
TYPE_UChar = _meshutils.TYPE_UChar
TYPE_Int16 = _meshutils.TYPE_Int16
TYPE_UInt16 = _meshutils.TYPE_UInt16
TYPE_Int32 = _meshutils.TYPE_Int32
TYPE_UInt32 = _meshutils.TYPE_UInt32
TYPE_Float32 = _meshutils.TYPE_Float32
TYPE_Float64 = _meshutils.TYPE_Float64

def errclear(*args):
  """errclear()"""
  return _meshutils.errclear(*args)

def mem_checkIntegrity(*args):
  """mem_checkIntegrity(int lineNo, char funName, char fileName, char dirName)"""
  return _meshutils.mem_checkIntegrity(*args)

def mem_statistics(*args):
  """mem_statistics(int lineNo, char funName, char fileName, char dirName)"""
  return _meshutils.mem_statistics(*args)

def mem_print(*args):
  """mem_print(FILE file, int32 mode) -> int32"""
  return _meshutils.mem_print(*args)

def mem_printSome(*args):
  """mem_printSome(FILE file, int32 mode, int32 num) -> int32"""
  return _meshutils.mem_printSome(*args)

def mem_freeGarbage(*args):
  """mem_freeGarbage() -> int32"""
  return _meshutils.mem_freeGarbage(*args)

def sys_pause(*args):
  """sys_pause()"""
  return _meshutils.sys_pause(*args)
__FUNC__ = _meshutils.__FUNC__

def f_checkMemoryIntegrity(*args):
  """f_checkMemoryIntegrity()"""
  return _meshutils.f_checkMemoryIntegrity(*args)

def f_printMemStats(*args):
  """f_printMemStats()"""
  return _meshutils.f_printMemStats(*args)

def sortRows(*args):
  """sortRows(int32 array, int32 iSortCol) -> int32"""
  return _meshutils.sortRows(*args)

def createList(*args):
  """
    createList(int32 p_ii, int32 objs, int32 ig, int32 conn0, int32 items, 
        int32 isSort) -> int32
    """
  return _meshutils.createList(*args)

def neighbourListPtr(*args):
  """
    neighbourListPtr(int32 pobj, int32 pg, int32 pel, int32 dataS, int32 ic, 
        int32 mode) -> int32
    """
  return _meshutils.neighbourListPtr(*args)

def neighbourList(*args):
  """
    neighbourList(int32 p_iu, int32 objs, int32 uid, int32 cnt, int32 pg, 
        int32 pel, int32 pobj, int32 dataS, int32 uidIn, 
        int32 ic, int32 perm, int32 mode) -> int32
    """
  return _meshutils.neighbourList(*args)

def orientEdges(*args):
  """orientEdges(int32 ori, int32 conn, int32 edges) -> int32"""
  return _meshutils.orientEdges(*args)

def assignEdgeNodes(*args):
  """
    assignEdgeNodes(int32 p_iseq, int32 econn, int32 cntEN, int32 ori, 
        int32 ntt, int32 uid, int32 edgeDesc, int32 cptr0) -> int32
    """
  return _meshutils.assignEdgeNodes(*args)

def interpVertexData(*args):
  """
    interpVertexData(float64 nodOut, int32 econn, float64 nodIn, int32 conn, 
        float64 bf, int32 omitCols) -> int32
    """
  return _meshutils.interpVertexData(*args)

def orientElements(*args):
  """
    orientElements(int32 flag, int32 conn, float64 coors, int32 vRoots, 
        int32 vVecs, int32 swapFrom, int32 swapTo) -> int32
    """
  return _meshutils.orientElements(*args)

def graphComponents(*args):
  """graphComponents(int32 p_nComp, int32 flag, int32 row, int32 col, int32 pos) -> int32"""
  return _meshutils.graphComponents(*args)


